@E_Commerce.API_HostAddress = http://localhost:5001

###Get Weatherforecast
@s=http://localhost:5001
GET {{E_Commerce.API_HostAddress}}/api/weatherforecast/
Accept: application/json

##weatherforecast
GET {{s}}/api/weatherforecast/G